version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: banco-postgres
    environment:
      POSTGRES_USER: alvaro
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banco-network

  backend:
    build:
      context: . 
      dockerfile: dev.Dockerfile
    container_name: banco-backend
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APP_NAME}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${JPA_DDL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - banco-network

volumes:
  postgres-data:

networks:
  banco-network:
    driver: bridge